// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzN-xX9v2UJvw8ewKiozsvBl7Fbgu5uW4',
    appId: '1:89415372170:android:189fcde23e548d6fbe8c73',
    messagingSenderId: '89415372170',
    projectId: 'anchor-alarm-28b19',
    databaseURL: 'https://anchor-alarm-28b19-default-rtdb.firebaseio.com',
    storageBucket: 'anchor-alarm-28b19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWjXV4yMPacQ57hzV9IC1BSf_HkuofOd0',
    appId: '1:89415372170:ios:556f1578a1dcc178be8c73',
    messagingSenderId: '89415372170',
    projectId: 'anchor-alarm-28b19',
    databaseURL: 'https://anchor-alarm-28b19-default-rtdb.firebaseio.com',
    storageBucket: 'anchor-alarm-28b19.firebasestorage.app',
    iosBundleId: 'com.sailorsparrot.anchoralarm',
  );
}
